### ISSUE TITLE
User Integration Testing

### ISSUE THREAD

**Issue by bretterer** [okta/okta-sdk-php#14]
## Scenarios
- [ ] Get User #23
- [ ] Activate User #24
- [ ] Update User Profile #25
- [ ] Suspend User #26 
- [ ] Change User Password #27 
- [ ] Get Reset Password URL #28 
- [ ] Expire User Password #29 
- [ ] Change User Recovery Question #30 
- [ ] Assign User Role #31 
- [ ] User Group Target Role #32
